Secret Test 33

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -25,6 +25,23 @@ jobs:
       
       - name: Set password and username secrets as environment variables
         run: |
+        
+          if [ -z "${{ secrets.MTC_PASSWD }}" ]; then 
+            echo "Secret MTC_PASSWD is missing!" 
+            exit 1 
+          fi 
+          if [ -z "${{ secrets.MTC_USERNAME }}" ]; then 
+            echo "Secret MTC_USERNAME is missing!" 
+            exit 1 
+          fi 
+          if [ -z "${{ secrets.ODS_USERNAME}}" ]; then 
+            echo "Secret ODS_USERNAME is missing!" 
+            exit 1 
+          fi 
+          if [ -z "${{ secrets.ODS_PASSWD }}" ]; then 
+            echo "Secret ODS_PASSWD is missing!" 
+            exit 1 
+          fi 
           
           echo "MTC_PASSWD=${{ secrets.MTC_PASSWOD }}" >> $GITHUB_ENV 
           echo "MTC_USERNAME=${{ secrets.MTC_USERNAME }}" >> $GITHUB_ENV 
