Secret Test 23

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -34,6 +34,14 @@ jobs:
             echo "Secret MTC_USERNAME is missing!" 
             exit 1 
           fi 
+          if [ -z "${{ secrets.ODS_USERNAME }}" ]; then 
+            echo "Secret ODS_USERNAME is missing!" 
+            exit 1 
+          fi 
+          if [ -z "${{ secrets.ODS_PASSWD }}" ]; then 
+            echo "Secret ODS_PASSWD is missing!" 
+            exit 1 
+          fi 
           echo "MTC_PASSWD=${{ secrets.MTC_PASSWD }}" >> $GITHUB_ENV 
           echo "MTC_USERNAME=${{ secrets.MTC_USERNAME }}" >> $GITHUB_ENV 
           echo "ODS_USERNAME=${{ secrets.ODS_USERNAME }}" >> $GITHUB_ENV 
