Secret Test 30

diff --git a/.github/workflows/dockertest.yml b/.github/workflows/dockertest.yml
--- a/.github/workflows/dockertest.yml
+++ b/.github/workflows/dockertest.yml
@@ -22,27 +22,38 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-       
+      
+       - name: Set password and username secrets as environment variables 
+
+        run: |
+#          if [ -z "${{ secrets.MTC_PASSWD }}" ]; then 
+#            echo "Secret MTC_PASSWD is missing!" 
+#            exit 1 
+#          fi 
+#          if [ -z "${{ secrets.MTC_USRNAME }}" ]; then 
+#            echo "Secret MTC_USRNAME is missing!" 
+#            exit 1 
+#          fi 
+          echo "MTC_PASSWD=${{ secrets.MTC_PASSWD }}" >> $GITHUB_ENV 
+          echo "MTC_USERNAME=${{ secrets.MTC_USERNAME }}" >> $GITHUB_ENV 
+          echo "ODS_USERNAME=${{ secrets.ODS_USERNAME }}" >> $GITHUB_ENV 
+          echo "ODS_PASSWD=${{ secrets.ODS_PASSWD }}" >> $GITHUB_ENV 
       - name: Run tests
         run: |
           if [ -f docker-compose.test.yml ]; then
             docker-compose --file docker-compose.test.yml build
             docker-compose --file docker-compose.test.yml run sut
           else
-           echo "MTC_PASSWD=${{ secrets.MTC_PASSWD }}" \
-                "MTC_USERNAME=${{ secrets.MTC_USERNAME }}" \
-                "ODS_USERNAME=${{ secrets.ODS_USERNAME }}" \
-                "ODS_PASSWD=${{ secrets.ODS_PASSWD }}" >> $GITHUB_ENV
-                
+          
             docker build \
             --no-cache \
             --secret id=MTC_PASSWD,env=MTC_PASSWD \
             --secret id=MTC_USERNAME,env=MTC_USERNAME \
             --secret id=ODS_USERNAME,env=ODS_USERNAME \
             --secret id=ODS_PASSWD,env=ODS_PASSWD \
-            --build-arg MTC_USERNAME="${{ secrets.MTC_USERNAME }}" \
-            --build-arg MTC_PASSWD="${{ secrets.MTC_PASSWD }}" \
-            --build-arg ODS_USERNAME="${{ secrets.ODS_USERNAME }}" \
-            --build-arg ODS_PASSWD="${{ secrets.ODS_PASSWD }}" . --file Dockerfile
+            --build-arg MTC_USERNAME="${MTC_USERNAME}" \
+            --build-arg MTC_PASSWD="${MTC_PASSWD}" \
+            --build-arg ODS_USERNAME="${ODS_USERNAME}" \
+            --build-arg ODS_PASSWD="${ODS_PASSWD}" . --file Dockerfile
           fi
           
